name: Stats Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 */2 * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: yunsii/stats-readme@main
